# SHEETY DETAILS
SHEETY_BASE_URL = ""

# TEQUILA DETAILS
TEQUILA_API_KEY = ""
TEQUILA_BASE_URL = "https://api.tequila.kiwi.com"

# TWILIO DETAILS
TWILIO_SID = ""
TWILIO_AUTH_TOKEN = ""
TWILIO_VIRTUAL_NUMBER = "+"
TWILIO_VERIFIED_NUMBER = "+"

# EMAIL DETAILS
SMTP_EMAIL = "calamp.validation@gmail.com"
SMTP_PASSWORD = ""
