print("Welcome to the tip calculator.")
expense = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would like to give? 10, 12, or 15? "))
num_of_people = int(input("How many people to split the bill? "))
each_person_pay = round((expense + (expense * (tip/100)))/num_of_people, 2)
print(f"Each person should pay: ${each_person_pay}")